# Generated by Django 5.1.1 on 2024-09-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_often_do_you_go_out', models.CharField(max_length=255)),
                ('how_would_you_describe_your_clothes', models.CharField(max_length=255)),
                ('how_do_you_spend_your_free_time', models.CharField(max_length=255)),
                ('how_many_times_do_you_visit_salon_or_beauty_parlour', models.IntegerField()),
                ('how_many_times_do_you_go_out_drinking_or_in_a_pub', models.IntegerField()),
                ('what_would_you_choose_for_a_romantic_date_with_your_partner', models.CharField(max_length=255)),
                ('which_social_platform_do_you_use_most', models.CharField(max_length=255)),
                ('do_you_like_shopping', models.BooleanField(default=False)),
                ('preferences_while_traveling', models.CharField(max_length=255)),
                ('which_personality_are_you', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=200)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='HabitsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=50)),
                ('drinking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=50)),
                ('food_preference', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non_Veg', 'Non-Vegetarian'), ('Egg', 'Eggetarian')], max_length=50)),
                ('sleep_habits', models.CharField(max_length=100)),
                ('exercise_habits', models.CharField(max_length=100)),
                ('other_habits', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HobbiesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoroscopeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('birth_place', models.CharField(max_length=100)),
                ('zodiac_sign', models.CharField(max_length=50)),
                ('horoscope_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='id_proofs/')),
                ('passport_size_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCompletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo_uploaded', models.BooleanField(default=False)),
                ('basic_details_completed', models.BooleanField(default=False)),
                ('education_details_completed', models.BooleanField(default=False)),
                ('horoscope_details_completed', models.BooleanField(default=False)),
                ('family_details_completed', models.BooleanField(default=False)),
                ('partner_preference_details_completed', models.BooleanField(default=False)),
                ('habits_details_completed', models.BooleanField(default=False)),
                ('hobbies_details_completed', models.BooleanField(default=False)),
                ('interest_details_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='SixPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='pic1/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='pic2/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='pic3/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='pic4/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='pic5/')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='pic6/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otherinfo.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.FloatField()),
                ('descriptions', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otherinfo.usermodel')),
            ],
        ),
    ]
